// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEacCqnT7X28AJvZVkaJCDTscFQIhWcVg',
    appId: '1:645899667333:web:f79126e77762854cd626ec',
    messagingSenderId: '645899667333',
    projectId: 'muhadir-7f83e',
    authDomain: 'muhadir-7f83e.firebaseapp.com',
    databaseURL: 'https://muhadir-7f83e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muhadir-7f83e.firebasestorage.app',
    measurementId: 'G-NMR6FPE10V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQOjXsTI3LUsfml_Sav2-4mN2J4Z9mOY',
    appId: '1:645899667333:android:6c70d5fb875d9b17d626ec',
    messagingSenderId: '645899667333',
    projectId: 'muhadir-7f83e',
    databaseURL: 'https://muhadir-7f83e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muhadir-7f83e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeX_boQNVAzE4mq_Jc1hVxU4dk27YIjcA',
    appId: '1:645899667333:ios:d43a4ef988a284c9d626ec',
    messagingSenderId: '645899667333',
    projectId: 'muhadir-7f83e',
    databaseURL: 'https://muhadir-7f83e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muhadir-7f83e.firebasestorage.app',
    iosBundleId: 'com.example.muhadirapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeX_boQNVAzE4mq_Jc1hVxU4dk27YIjcA',
    appId: '1:645899667333:ios:d43a4ef988a284c9d626ec',
    messagingSenderId: '645899667333',
    projectId: 'muhadir-7f83e',
    databaseURL: 'https://muhadir-7f83e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muhadir-7f83e.firebasestorage.app',
    iosBundleId: 'com.example.muhadirapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEacCqnT7X28AJvZVkaJCDTscFQIhWcVg',
    appId: '1:645899667333:web:dc2ede4da5fc5482d626ec',
    messagingSenderId: '645899667333',
    projectId: 'muhadir-7f83e',
    authDomain: 'muhadir-7f83e.firebaseapp.com',
    databaseURL: 'https://muhadir-7f83e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muhadir-7f83e.firebasestorage.app',
    measurementId: 'G-N1VH3Q69SX',
  );

}