import '../../../models/attendance/manual_attendance_record.dart';
import '../../../models/attendance/manual_attendance_session.dart';
import '../../../models/external_student.dart';
import '../../../repositories/lecturer_catalog_repository.dart';
import '../../../utils/localized_firestore_fields.dart';
import '../../lecturer_auth_service.dart';
import '../../lecturer/lecturer_course_name_index.dart';
import '../attendance_student_card_calculator.dart'
    show AbsenceCardPercentages, StudentSectionAbsenceMetrics;
import '../manual_attendance_service.dart';
import '../student_section_absence_service.dart';
import 'attendance_session_export_locale.dart';

class AttendanceSessionExportStudentRow {
  const AttendanceSessionExportStudentRow({
    required this.recordId,
    required this.studentId,
    required this.studentName,
    required this.status,
    required this.statusLabel,
    required this.statusCode,
    required this.attendanceTime,
    this.courseCode = '',
    required this.lectureStartTime,
    required this.lectureEndTime,
    required this.totalAbsencePctDisplay,
    required this.unexcusedAbsencePctDisplay,
    required this.excusedAbsencePctDisplay,
    required this.deprivationLabel,
    required this.isAcademicallyDeprived,
  });

  final String recordId;
  final int studentId;
  final String studentName;
  final ManualAttendanceStatus status;
  final String statusLabel;
  final String statusCode;
  final String attendanceTime;
  final String courseCode;
  final String lectureStartTime;
  final String lectureEndTime;
  final String totalAbsencePctDisplay;
  final String unexcusedAbsencePctDisplay;
  final String excusedAbsencePctDisplay;
  final String deprivationLabel;
  final bool isAcademicallyDeprived;
}

class AttendanceSessionExportSummary {
  const AttendanceSessionExportSummary({
    required this.totalStudents,
    required this.pendingCount,
    required this.presentCount,
    required this.absentCount,
    required this.excusedCount,
    required this.lateCount,
    this.presentPct,
    this.absentPct,
    this.excusedPct,
    this.latePct,
    required this.sessionAttendancePct,
    required this.sessionAbsencePct,
    required this.deprivedStudentsCount,
  });

  final int totalStudents;
  final int pendingCount;
  final int presentCount;
  final int absentCount;
  final int excusedCount;
  final int lateCount;
  final String? presentPct;
  final String? absentPct;
  final String? excusedPct;
  final String? latePct;
  final String sessionAttendancePct;
  final String sessionAbsencePct;
  final int deprivedStudentsCount;
}

/// Shared snapshot for CSV and PDF export (single session).
class AttendanceSessionExportModel {
  const AttendanceSessionExportModel({
    required this.session,
    required this.locale,
    required this.localizedCourseName,
    required this.sectionDisplay,
    required this.lectureDateIso,
    required this.lectureTimeRange,
    required this.dayOfWeekLabel,
    required this.generatedAtUtc,
    required this.generatedAtDisplay,
    required this.lecturerName,
    required this.isDefaultPresent,
    required this.attendanceMethodLabel,
    required this.summary,
    required this.students,
  });

  final ManualAttendanceSession session;
  final AttendanceSessionExportLocale locale;
  final String localizedCourseName;
  final String sectionDisplay;
  final String lectureDateIso;
  final String lectureTimeRange;
  final String dayOfWeekLabel;
  final DateTime generatedAtUtc;
  final String generatedAtDisplay;
  final String lecturerName;
  final bool isDefaultPresent;
  final String attendanceMethodLabel;
  final AttendanceSessionExportSummary summary;
  final List<AttendanceSessionExportStudentRow> students;
}

class AttendanceSessionExportModelBuilder {
  AttendanceSessionExportModelBuilder._();

  static final ManualAttendanceService _manual = ManualAttendanceService.instance;

  static bool isDefaultPresentSessionData(Map<String, dynamic> data) {
    if (data['sessionWasOpened'] == true) return false;
    final method = (data['attendanceMethod'] ?? '').toString().trim();
    if (_isRealOpenedAttendanceMethod(method)) return false;
    if (data['defaultPresentPolicyApplied'] == true) return true;
    if (method == ManualAttendanceService.attendanceMethodDefaultPresent) {
      return true;
    }
    return data['autoGenerated'] == true && data['sessionWasOpened'] == false;
  }

  static bool _isRealOpenedAttendanceMethod(String method) {
    switch (method.trim().toLowerCase()) {
      case 'manual':
      case 'qr':
      case 'nfc':
      case 'bluetooth':
        return true;
      default:
        return false;
    }
  }

  static Future<AttendanceSessionExportModel> build({
    required String sessionId,
    bool? isArabic,
  }) async {
    final sid = sessionId.trim();
    if (sid.isEmpty) {
      throw StateError('sessionId is empty');
    }

    final locale = AttendanceSessionExportLocale.fromLanguage(isArabic: isArabic);
    final arabic = locale.isArabic;

    final session = await _manual.getSessionById(sid);
    if (session == null) {
      throw StateError('Session not found');
    }

    final owns = await _currentLecturerOwnsSection(session.sectionId);
    if (!owns) {
      throw StateError('Not authorized to export this session');
    }

    await _ensureCourseNameIndex();

    final raw = await _manual.getSessionRawDataById(sid) ?? <String, dynamic>{};
    final isDefaultPresent = isDefaultPresentSessionData(raw);

    // Unchanged: getRecordsForSessionIds may finalize pending → absent (non-default).
    final grouped = await _manual.getRecordsForSessionIds({sid});
    final records = List<ManualAttendanceRecord>.from(
      grouped[sid] ?? const <ManualAttendanceRecord>[],
    );

    final studentIds = records.map((r) => r.studentId).where((id) => id > 0).toSet();
    final profiles = await _manual.fetchStudentProfilesByIds(studentIds);

    final courseCode = (session.courseCode ?? '').trim();
    final absenceMetrics =
        await StudentSectionAbsenceService.instance.loadAbsenceMetricsByStudentId(
      sectionId: session.sectionId,
      courseCode: courseCode.isNotEmpty ? courseCode : session.sectionId,
    );

    final courseNames = _resolveCourseNames(session, raw);
    final localizedCourseName = LocalizedFirestoreFields.localizedCourseName(
      <String, dynamic>{
        'courseNameAr': courseNames.ar,
        'courseNameEn': courseNames.en,
        'courseName': session.courseName,
        ...raw,
      },
      isArabic: arabic,
      fallback: (session.courseCode ?? '').trim().isNotEmpty
          ? session.courseCode!
          : session.sectionId,
    );

    final sectionDisplay = locale.sectionDisplayLabel(session.sectionLabel);
    final lecturerName = _localizedLecturerName(arabic);

    final nowUtc = DateTime.now().toUtc();
    final generatedAtDisplay = _formatGeneratedAt(nowUtc, arabic);

    final students = records.map((record) {
      final name = _localizedStudentName(
        record: record,
        profile: profiles[record.studentId],
        isArabic: arabic,
      );
      final metrics = absenceMetrics[record.studentId];
      final deprived = metrics?.isAcademicallyDeprived ?? false;
      return AttendanceSessionExportStudentRow(
        recordId: record.recordId,
        studentId: record.studentId,
        studentName: name,
        status: record.status,
        statusLabel: locale.statusLabel(record.status),
        statusCode: ManualAttendanceRecord.statusToString(record.status),
        attendanceTime: record.attendanceTime,
        courseCode: record.courseCode ?? '',
        lectureStartTime: record.lectureStartTime,
        lectureEndTime: record.lectureEndTime,
        totalAbsencePctDisplay: _semesterPctDisplay(
          metrics,
          (b) => b.totalAbsencePct,
        ),
        unexcusedAbsencePctDisplay: _semesterPctDisplay(
          metrics,
          (b) => b.unexcusedPct,
        ),
        excusedAbsencePctDisplay: _semesterPctDisplay(
          metrics,
          (b) => b.excusedPct,
        ),
        deprivationLabel: deprived ? locale.deprivedYes : locale.deprivedNo,
        isAcademicallyDeprived: deprived,
      );
    }).toList()
      ..sort((a, b) => a.studentName.compareTo(b.studentName));

    final deprivedCount =
        students.where((s) => s.isAcademicallyDeprived).length;
    final summary = _buildSummary(
      records,
      deprivedStudentsCount: deprivedCount,
    );

    final rawMethod = (raw['attendanceMethod'] ?? '').toString();
    final methodLabel = locale.attendanceMethodLabel(
      rawMethod,
      isDefaultPresent: isDefaultPresent,
    );

    final d = session.lectureDate;
    final lectureDateIso =
        '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

    return AttendanceSessionExportModel(
      session: session,
      locale: locale,
      localizedCourseName: localizedCourseName,
      sectionDisplay: sectionDisplay,
      lectureDateIso: lectureDateIso,
      lectureTimeRange: '${session.lectureStartTime} - ${session.lectureEndTime}',
      dayOfWeekLabel: locale.dayNameFromWeekday(session.dayOfWeek),
      generatedAtUtc: nowUtc,
      generatedAtDisplay: generatedAtDisplay,
      lecturerName: lecturerName,
      isDefaultPresent: isDefaultPresent,
      attendanceMethodLabel: methodLabel,
      summary: summary,
      students: students,
    );
  }

  static String _semesterPctDisplay(
    StudentSectionAbsenceMetrics? metrics,
    double Function(AbsenceCardPercentages breakdown) pick,
  ) {
    if (metrics == null) return '0%';
    final b = metrics.breakdown;
    return '${b.displayFloor(pick(b))}%';
  }

  static AttendanceSessionExportSummary _buildSummary(
    List<ManualAttendanceRecord> records, {
    required int deprivedStudentsCount,
  }) {
    var pending = 0, p = 0, a = 0, e = 0, l = 0;
    for (final r in records) {
      switch (r.status) {
        case ManualAttendanceStatus.pending:
          pending++;
          break;
        case ManualAttendanceStatus.present:
          p++;
          break;
        case ManualAttendanceStatus.absent:
          a++;
          break;
        case ManualAttendanceStatus.excused:
          e++;
          break;
        case ManualAttendanceStatus.late:
          l++;
          break;
      }
    }
    final total = records.length;
    String? pct(int count) =>
        total > 0 ? ((count / total) * 100).toStringAsFixed(2) : null;

    final attended = p + l;
    final sessionAbsent = a + e;
    final attendancePct = total > 0
        ? ((attended / total) * 100).toStringAsFixed(2)
        : '0.00';
    final absencePct = total > 0
        ? ((sessionAbsent / total) * 100).toStringAsFixed(2)
        : '0.00';

    return AttendanceSessionExportSummary(
      totalStudents: total,
      pendingCount: pending,
      presentCount: p,
      absentCount: a,
      excusedCount: e,
      lateCount: l,
      presentPct: pct(p),
      absentPct: pct(a),
      excusedPct: pct(e),
      latePct: pct(l),
      sessionAttendancePct: attendancePct,
      sessionAbsencePct: absencePct,
      deprivedStudentsCount: deprivedStudentsCount,
    );
  }

  static _CourseNames _resolveCourseNames(
    ManualAttendanceSession session,
    Map<String, dynamic> raw,
  ) {
    final sectionId = session.sectionId.trim();
    final courseCode = (session.courseCode ?? '').trim();
    final fromIndex = LecturerCourseNameIndex.instance.lookup(
      courseCode: courseCode,
      sectionId: sectionId,
    );

    var ar = fromIndex?.ar ?? '';
    var en = fromIndex?.en ?? '';

    if (ar.isEmpty || en.isEmpty) {
      ar = ar.isNotEmpty
          ? ar
          : LocalizedFirestoreFields.localizedCourseName(
              raw,
              isArabic: true,
              fallback: session.courseName,
            );
      en = en.isNotEmpty
          ? en
          : LocalizedFirestoreFields.localizedCourseName(
              raw,
              isArabic: false,
              fallback: session.courseName,
            );
    }

    final snapshot = session.courseName.trim();
    if (en.isEmpty && snapshot.isNotEmpty) en = snapshot;
    if (ar.isEmpty && en.isNotEmpty) ar = en;
    if (en.isEmpty && ar.isNotEmpty) en = ar;

    return _CourseNames(ar: ar, en: en);
  }

  static String _localizedStudentName({
    required ManualAttendanceRecord record,
    required ExternalStudent? profile,
    required bool isArabic,
  }) {
    if (profile != null) {
      return profile.displayNameFor(isArabic);
    }
    return LocalizedFirestoreFields.localizedPersonName(
      <String, dynamic>{'studentName': record.studentName},
      isArabic: isArabic,
      fallback: record.studentId > 0
          ? '${record.studentId}'
          : record.studentName,
    );
  }

  static String _localizedLecturerName(bool isArabic) {
    final lecturer = LecturerAuthService.instance.currentLecturer;
    if (lecturer == null) return '';
    return lecturer.displayNameFor(isArabic);
  }

  static String _formatGeneratedAt(DateTime utc, bool isArabic) {
    final local = utc.toLocal();
    final date =
        '${local.year}-${local.month.toString().padLeft(2, '0')}-${local.day.toString().padLeft(2, '0')}';
    final time =
        '${local.hour.toString().padLeft(2, '0')}:${local.minute.toString().padLeft(2, '0')}';
    if (isArabic) {
      return '$date $time';
    }
    return '$date $time (local)';
  }

  static Future<void> _ensureCourseNameIndex() async {
    final lecturerId =
        LecturerAuthService.instance.currentLecturer?.lecturerId.trim() ?? '';
    if (lecturerId.isEmpty) return;
    try {
      final catalog =
          await LecturerCatalogRepository.instance.getCatalogForLecturer(
        lecturerId,
      );
      LecturerCourseNameIndex.instance.updateFromCatalog(catalog);
    } catch (_) {
      // Index optional; session/catalog fallbacks still apply.
    }
  }

  static Future<bool> _currentLecturerOwnsSection(String sectionId) async {
    final want = sectionId.trim();
    if (want.isEmpty) return false;
    final lecturerId =
        LecturerAuthService.instance.currentLecturer?.lecturerId.trim() ?? '';
    if (lecturerId.isEmpty) return false;
    final catalog =
        await LecturerCatalogRepository.instance.getCatalogForLecturer(
      lecturerId,
    );
    return catalog.sectionIds.contains(want);
  }
}

class _CourseNames {
  const _CourseNames({required this.ar, required this.en});
  final String ar;
  final String en;
}
